"""Tests for the Drydock CLI entry point."""

from __future__ import annotations

import pytest

from drydock import __copyright__, __version__
from drydock.cli import main


def run_cli(*args: str) -> tuple[int, str, str]:
    """Run main() in-process, capturing stdout/stderr and exit code."""
    import io
    from contextlib import redirect_stderr, redirect_stdout

    out = io.StringIO()
    err = io.StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        try:
            main(list(args))
        except SystemExit as exc:
            rc = int(exc.code) if exc.code is not None else 0
        else:
            rc = 0
    return rc, out.getvalue(), err.getvalue()


class TestHelpAndVersion:
    def test_help_shows_copyright(self):
        rc, out, err = run_cli("--help")
        assert rc == 0
        assert __copyright__ in out
        assert "Blueprint-driven" in out

    def test_help_shows_all_top_commands(self):
        rc, out, _ = run_cli("--help")
        for cmd in (
            "status",
            "config",
            "init",
            "validate",
            "document",
            "rigging",
            "plan",
            "build",
            "refit",
            "analyze",
            "import",
            "run",
        ):
            assert cmd in out, f"Command {cmd!r} missing from --help"

    def test_help_does_not_expose_ships_log(self):
        rc, out, _ = run_cli("--help")
        assert rc == 0
        assert "log" not in out

    def test_version_shows_version_and_copyright(self):
        rc, out, err = run_cli("--version")
        # argparse prints version to stdout
        combined = out + err
        assert __version__ in combined
        assert __copyright__ in combined

    def test_no_args_shows_help(self):
        rc, out, _ = run_cli()
        assert rc == 0
        assert "drydock" in out.lower()


class TestConfigShow:
    def test_config_show_runs(self, isolated_config):
        rc, out, err = run_cli("config", "show")
        assert rc == 0
        assert "drydock_workspace" in out

    def test_config_show_defaults_when_unset(self, isolated_config):
        rc, out, _ = run_cli("config", "show")
        assert rc == 0
        assert "drydock_workspace" in out
        assert "(default)" in out


class TestConfigSet:
    def test_config_set_valid(self, tmp_workspace, isolated_config):
        rc, out, err = run_cli("config", "set", "drydock_workspace", str(tmp_workspace))
        assert rc == 0
        assert "drydock_workspace" in out

    def test_config_set_persists(self, tmp_workspace, isolated_config):
        run_cli("config", "set", "drydock_workspace", str(tmp_workspace))
        rc, out, _ = run_cli("config", "show")
        assert str(tmp_workspace) in out

    def test_config_set_nonexistent_dir_fails(self, isolated_config):
        rc, out, err = run_cli("config", "set", "drydock_workspace", "/does/not/exist")
        assert rc == 1
        assert "error" in err.lower()

    def test_config_set_llm_provider(self, isolated_config):
        rc, out, err = run_cli("config", "set", "llm_provider", "codex")
        assert rc == 0
        assert "codex" in out

    def test_config_set_prompt_warn_kb(self, isolated_config):
        rc, out, err = run_cli("config", "set", "prompt_warn_kb", "75")
        assert rc == 0
        assert "75" in out

    def test_config_set_invalid_prompt_warn_kb_fails(self, isolated_config):
        rc, out, err = run_cli("config", "set", "prompt_warn_kb", "fifty")
        assert rc == 1
        assert "error" in err.lower()


class TestInit:
    def test_init_creates_target_baseline(self, tmp_target_root, isolated_config):
        run_cli("config", "set", "drydock_workspace", str(tmp_target_root.parent))
        rc, out, err = run_cli("init", "TestProject")
        assert rc == 0
        target = tmp_target_root / "TestProject"
        assert "Target:" in out
        for path in (
            "METADATA.md",
            "blueprint/sources/.gitkeep",
            "evidence/.gitkeep",
            "logs/.gitkeep",
            "QuarterDeck/console.yaml",
            "QuarterDeck/tickets.json",
            "QuarterDeck/pages/overview.md",
        ):
            assert (target / path).is_file(), f"{path} missing"
        # SEA_TRIALS.md and SOUNDINGS.md are generated by analyze, not init.
        assert not (target / "SEA_TRIALS.md").is_file()
        assert not (target / "SOUNDINGS.md").is_file()
        # The console runtime is served from the package, not copied into the target.
        assert not (target / "QuarterDeck" / "app.py").exists()
        assert not (target / "QuarterDeck" / "requirements.txt").exists()
        assert not (target / "target.yaml").exists()
        assert not (target / "docs").exists()

    def test_init_is_idempotent_and_preserves_existing_files(
        self, tmp_target_root, isolated_config
    ):
        run_cli("config", "set", "drydock_workspace", str(tmp_target_root.parent))
        run_cli("init", "TestProject")
        overview = tmp_target_root / "TestProject" / "QuarterDeck" / "pages" / "overview.md"
        overview.write_text("CUSTOM", encoding="utf-8")

        rc, out, err = run_cli("init", "TestProject")

        assert rc == 0
        assert overview.read_text(encoding="utf-8") == "CUSTOM"
        assert "existing baseline files preserved" in out

    def test_init_rejects_blueprint_options(self, tmp_target_root, isolated_config):
        run_cli("config", "set", "drydock_workspace", str(tmp_target_root.parent))
        rc, out, err = run_cli("init", "TestProject", "--force")
        assert rc == 2

    def test_init_rejects_path_traversal(self, tmp_target_root, isolated_config):
        run_cli("config", "set", "drydock_workspace", str(tmp_target_root.parent))
        rc, out, err = run_cli("init", "../evil")
        assert rc == 1

    def test_init_rejects_empty_name(self, tmp_target_root, isolated_config):
        run_cli("config", "set", "drydock_workspace", str(tmp_target_root.parent))
        rc, out, err = run_cli("init", "")
        assert rc != 0


class TestValidate:
    def _setup_spec(self, tmp_target_root, isolated_config):
        from drydock.init_specification import init_specification

        run_cli("config", "set", "drydock_workspace", str(tmp_target_root.parent))
        target_dir = tmp_target_root / "TestProject"
        init_specification("TestProject", target_dir)
        return target_dir

    def test_validate_after_init_exits_zero(self, tmp_target_root, isolated_config):
        self._setup_spec(tmp_target_root, isolated_config)
        rc, out, err = run_cli("validate", "TestProject")
        assert rc == 0  # warnings are OK, no failures expected after init

    def test_validate_nonexistent_spec_fails(self, tmp_target_root, isolated_config):
        run_cli("config", "set", "drydock_workspace", str(tmp_target_root.parent))
        rc, out, err = run_cli("validate", "DoesNotExist")
        assert rc == 1

    def test_validate_verbose_shows_passes(self, tmp_target_root, isolated_config):
        self._setup_spec(tmp_target_root, isolated_config)
        rc_plain, out_plain, _ = run_cli("validate", "TestProject")
        rc_verb, out_verb, _ = run_cli("validate", "TestProject", "--verbose")
        assert rc_verb == 0
        assert "PASS" in out_verb
        assert len(out_verb) > len(out_plain)

    def test_validate_missing_required_file_fails(self, tmp_target_root, isolated_config):
        target_dir = self._setup_spec(tmp_target_root, isolated_config)
        # Put target in Implement phase so ARCHITECTURE.md is required
        (target_dir / "BUILD_PLAN.md").write_text("# Build Plan\n", encoding="utf-8")
        (target_dir / "blueprint" / "ARCHITECTURE.md").unlink()
        rc, out, err = run_cli("validate", "TestProject")
        assert rc == 1
        assert "ARCHITECTURE" in out

    def test_validate_shows_result_summary(self, tmp_target_root, isolated_config):
        self._setup_spec(tmp_target_root, isolated_config)
        rc, out, _ = run_cli("validate", "TestProject")
        assert "✓" in out or "✗" in out or "⚠" in out


class TestRiggingCompact:
    """`rigging compact` discovers stale files and writes _compact.md siblings."""

    @staticmethod
    def _fake_run_prompt(monkeypatch, *, ok=True, text="# X — Compact\n\n- must stay\n"):
        from types import SimpleNamespace

        def fake(prompt, working_directory, **kwargs):
            return SimpleNamespace(ok=ok, text=text, execution_id="exec-test")

        monkeypatch.setattr("drydock.rigging_compact.run_prompt", fake)

    def _setup_blueprint(self, tmp_target_root, name="Proj", **files):
        run_cli("config", "set", "drydock_workspace", str(tmp_target_root.parent))
        spec = tmp_target_root / name / "blueprint"
        spec.mkdir(parents=True)
        for fname, body in (files or {"DATABASE.md": "class X: ...\n"}).items():
            (spec / fname).write_text(body, encoding="utf-8")
        return spec

    def test_help_lists_flags(self):
        rc, out, _ = run_cli("rigging", "compact", "--help")
        assert rc == 0
        assert "--all" in out and "--force" in out

    def test_compacts_and_reports(self, tmp_target_root, isolated_config, monkeypatch):
        spec = self._setup_blueprint(tmp_target_root)
        self._fake_run_prompt(monkeypatch)
        rc, out, err = run_cli("rigging", "compact", "Proj")
        assert rc == 0, err
        assert (spec / "DATABASE_compact.md").exists()
        assert "1 compacted" in out
        assert "exec-test" in out

    def test_failed_execution_exits_one(self, tmp_target_root, isolated_config, monkeypatch):
        self._setup_blueprint(tmp_target_root)
        self._fake_run_prompt(monkeypatch, ok=False, text="")
        rc, out, err = run_cli("rigging", "compact", "Proj")
        assert rc == 1
        assert "1 failed" in out

    def test_nothing_to_compact(self, tmp_target_root, isolated_config, monkeypatch):
        self._setup_blueprint(tmp_target_root, **{"README.md": "no compactables\n"})
        self._fake_run_prompt(monkeypatch)
        rc, out, err = run_cli("rigging", "compact", "Proj")
        assert rc == 0
        assert "Nothing to compact" in out


class TestPlanInspection:
    PLAN = """# BUILD_PLAN: Example
updated: 2026-06-11T12:00:00
plan_hash: abc123

## story 1: Foundation
id: foundation
state: closed/verified

## story 2: Import documents
id: import-documents
depends: foundation
state: pending

## story 3: Awaiting checks
id: awaiting-checks
state: implemented

## ac 1: System starts
id: system-starts
parent: awaiting-checks
state: pending
"""

    def _setup(self, tmp_target_root, monkeypatch):
        target = tmp_target_root / "ExampleTarget"
        target.mkdir()
        (target / "BUILD_PLAN.md").write_text(self.PLAN, encoding="utf-8")
        monkeypatch.setenv("DRYDOCK_WORKSPACE", str(tmp_target_root.parent))

    def test_build_status_reports_runnable_frontier(
        self, tmp_target_root, isolated_config, monkeypatch
    ):
        self._setup(tmp_target_root, monkeypatch)

        rc, out, err = run_cli("build", "status", "ExampleTarget")

        assert rc == 0, err
        assert f"Target: {tmp_target_root / 'ExampleTarget'}" in out
        assert "RUNNABLE        story import-documents" in out
        assert "RUNNABLE        ac    system-starts" in out
        assert "Runnable frontier: import-documents, system-starts" in out

    def test_build_status_usage_error(self):
        rc, out, err = run_cli("build", "status")

        assert rc == 2
        assert "Usage: drydock build status" in err


class TestPlanningSession:
    def _configure(self, tmp_target_root, monkeypatch):
        monkeypatch.setenv("DRYDOCK_WORKSPACE", str(tmp_target_root.parent))

    def test_markdown_import_plan_create_and_approve(
        self, tmp_path, tmp_target_root, isolated_config, monkeypatch
    ):
        self._configure(tmp_target_root, monkeypatch)
        source = tmp_path / "request.md"
        source.write_text(
            "# Request\n\nBuild a status command.\n\n## Acceptance Criteria\n\n"
            "- Status command exits successfully.\n",
            encoding="utf-8",
        )

        rc, out, err = run_cli("import", "ExampleTarget", str(source), "--format", "markdown")
        assert rc == 0, err
        bp = tmp_target_root / "ExampleTarget" / "blueprint"
        assert (bp / "sources" / "request.md").is_file()

        rc, out, err = run_cli("plan", "create", "ExampleTarget")
        assert rc == 0, err
        assert "Plan state: draft" in out
        assert (bp / "BUILD_PLAN_COMPASS.md").is_file()
        plan_path = tmp_target_root / "ExampleTarget" / "BUILD_PLAN.md"
        assert "Status command exits successfully." in plan_path.read_text(encoding="utf-8")
        quarterdeck = tmp_target_root / "ExampleTarget" / "QuarterDeck"
        assert (quarterdeck / "console.yaml").is_file()
        assert (quarterdeck / "tickets.json").is_file()
        assert not (quarterdeck / "app.py").exists()
        # SEA_TRIALS.md and SOUNDINGS.md are generated by analyze, not plan create.
        assert not (tmp_target_root / "ExampleTarget" / "SEA_TRIALS.md").is_file()
        config = (quarterdeck / "console.yaml").read_text(encoding="utf-8")
        assert config.index('label: "Sea Trials"') < config.index('label: "Soundings"')

        rc, out, err = run_cli("build", "status", "ExampleTarget")
        assert rc == 0, err
        assert "Runnable frontier: (none)" in out

        from drydock.build_plan import set_plan_state

        set_plan_state(plan_path, "approved", decision="approve")
        rc, out, err = run_cli("build", "status", "ExampleTarget")
        assert rc == 0, err
        assert "Runnable frontier: story-request" in out

    def test_feature_spec_generates_feature_parent_and_acceptance(
        self, tmp_target_root, isolated_config, monkeypatch
    ):
        self._configure(tmp_target_root, monkeypatch)
        blueprint = tmp_target_root / "Target" / "blueprint"
        blueprint.mkdir(parents=True)
        (blueprint / "FEATURE-Catalog.md").write_text(
            "# FEATURE: Catalog\n\n## Acceptance Criteria\n\n- Catalog lists items.\n"
            "\n## Guardrails\n\n- None.\n\n## Open Questions\n\n- Which sort order?\n",
            encoding="utf-8",
        )
        rc, out, err = run_cli("plan", "create", "Target")

        assert rc == 0, err
        text = (tmp_target_root / "Target" / "BUILD_PLAN.md").read_text(encoding="utf-8")
        assert "## feature 1: Catalog" in text
        assert "parent: feature-catalog" in text
        assert "Catalog workflow is accepted" in text
        assert "Which sort order?" in text
        assert "depends: spike-which-sort-order" in text

    @pytest.mark.parametrize("verb", ["init", "show", "approve", "revise", "reject"])
    def test_only_plan_create_is_public(self, verb):
        rc, out, err = run_cli("plan", verb, "Example", "Target")

        assert rc == 2
        assert "invalid choice" in err


class TestImport:
    def _configure(self, tmp_target_root, monkeypatch):
        monkeypatch.setenv("DRYDOCK_WORKSPACE", str(tmp_target_root.parent))

    def test_import_markdown_copies_source_file(
        self, tmp_path, tmp_target_root, isolated_config, monkeypatch
    ):
        self._configure(tmp_target_root, monkeypatch)
        source = tmp_path / "spec.md"
        source.write_text("# Spec\n", encoding="utf-8")

        rc, out, err = run_cli("import", "Tgt", str(source), "--format", "markdown")

        assert rc == 0, err
        assert (tmp_target_root / "Tgt" / "blueprint" / "sources" / "spec.md").is_file()

    def test_import_markdown_prints_imported_paths(
        self, tmp_path, tmp_target_root, isolated_config, monkeypatch
    ):
        self._configure(tmp_target_root, monkeypatch)
        source = tmp_path / "req.md"
        source.write_text("# Req\n", encoding="utf-8")

        rc, out, err = run_cli("import", "Tgt", str(source), "--format", "markdown")

        assert rc == 0, err
        assert "IMPORTED" in out
        assert "sources/req.md" in out

    def test_import_markdown_auto_detects_markdown_file(
        self, tmp_path, tmp_target_root, isolated_config, monkeypatch
    ):
        self._configure(tmp_target_root, monkeypatch)
        source = tmp_path / "spec.md"
        source.write_text("# Spec\n", encoding="utf-8")

        rc, out, err = run_cli("import", "Tgt", str(source), "--format", "auto")

        assert rc == 0, err
        assert (tmp_target_root / "Tgt" / "blueprint" / "sources" / "spec.md").is_file()

    def test_import_markdown_auto_detects_markdown_directory(
        self, tmp_path, tmp_target_root, isolated_config, monkeypatch
    ):
        self._configure(tmp_target_root, monkeypatch)
        src_dir = tmp_path / "docs"
        src_dir.mkdir()
        (src_dir / "spec.md").write_text("# Spec\n", encoding="utf-8")

        rc, out, err = run_cli("import", "Tgt", str(src_dir), "--format", "auto")

        assert rc == 0, err
        assert (tmp_target_root / "Tgt" / "blueprint" / "sources" / "spec.md").is_file()

    def test_import_missing_source_returns_1(
        self, tmp_path, tmp_target_root, isolated_config, monkeypatch
    ):
        self._configure(tmp_target_root, monkeypatch)

        rc, out, err = run_cli(
            "import", "Tgt", str(tmp_path / "nonexistent.md"), "--format", "markdown"
        )

        assert rc == 1

    def test_import_source_copies_code_files(
        self, tmp_path, tmp_target_root, isolated_config, monkeypatch
    ):
        self._configure(tmp_target_root, monkeypatch)
        src_dir = tmp_path / "myapp"
        src_dir.mkdir()
        (src_dir / "app.py").write_text("x = 1\n", encoding="utf-8")

        rc, out, err = run_cli("import", "Tgt", str(src_dir), "--format", "source")

        assert rc == 0, err
        assert (tmp_target_root / "Tgt" / "blueprint" / "sources" / "app.py").is_file()
        assert "IMPORTED" in out

    def test_import_source_auto_detects_code_directory(
        self, tmp_path, tmp_target_root, isolated_config, monkeypatch
    ):
        self._configure(tmp_target_root, monkeypatch)
        src_dir = tmp_path / "myapp"
        src_dir.mkdir()
        (src_dir / "app.py").write_text("x = 1\n", encoding="utf-8")

        rc, out, err = run_cli("import", "Tgt", str(src_dir), "--format", "auto")

        assert rc == 0, err
        assert (tmp_target_root / "Tgt" / "blueprint" / "sources" / "app.py").is_file()

    def test_import_speckit_copies_specify_structure(
        self, tmp_path, tmp_target_root, isolated_config, monkeypatch
    ):
        self._configure(tmp_target_root, monkeypatch)
        src_dir = tmp_path / "sk"
        (src_dir / ".specify" / "memory").mkdir(parents=True)
        (src_dir / ".specify" / "memory" / "constitution.md").write_text("# C\n", encoding="utf-8")

        rc, out, err = run_cli("import", "Tgt", str(src_dir), "--format", "speckit")

        assert rc == 0, err
        assert (
            tmp_target_root
            / "Tgt"
            / "blueprint"
            / "sources"
            / ".specify"
            / "memory"
            / "constitution.md"
        ).is_file()
        assert "IMPORTED" in out

    def test_import_speckit_auto_detects_speckit_directory(
        self, tmp_path, tmp_target_root, isolated_config, monkeypatch
    ):
        self._configure(tmp_target_root, monkeypatch)
        src_dir = tmp_path / "sk"
        (src_dir / ".specify" / "memory").mkdir(parents=True)
        (src_dir / ".specify" / "memory" / "constitution.md").write_text("# C\n", encoding="utf-8")

        rc, out, err = run_cli("import", "Tgt", str(src_dir), "--format", "auto")

        assert rc == 0, err
        assert (
            tmp_target_root
            / "Tgt"
            / "blueprint"
            / "sources"
            / ".specify"
            / "memory"
            / "constitution.md"
        ).is_file()

    def test_import_help_shows_arguments(self):
        rc, out, err = run_cli("import", "--help")
        assert rc == 0
        combined = out + err
        assert "<Target>" in combined
        assert "<Source>" in combined


class TestStubs:
    """Deferred commands must exit 2, print a message, and not write anything."""

    STUB_CASES = [
        (["document", "generate", "MyTarget"], "document generate"),
        (["document", "MyTarget"], "document"),
        (["rigging", "update", "MyTarget"], "rigging update"),
        (["rigging", "verify", "MyTarget"], "rigging verify"),
        (["build", "score", "MyTarget"], "build score"),
        (["build", "MyTarget"], "build"),
        (["refit", "MyTarget", "BOTH", "SomeScope", "SomeChange"], "refit"),
        (["refit", "MyTarget", "SPEC", "SomeScope", "SomeChange"], "refit"),
    ]

    @pytest.mark.parametrize("args,label", STUB_CASES)
    def test_stub_exits_2(self, args, label, tmp_path):
        rc, out, err = run_cli(*args)
        assert rc == 2, f"{label!r} should exit 2, got {rc}"

    @pytest.mark.parametrize("args,label", STUB_CASES)
    def test_stub_prints_not_implemented(self, args, label, tmp_path):
        rc, out, err = run_cli(*args)
        combined = out + err
        assert "not implemented" in combined, f"{label!r}: expected 'not implemented' in output"

    @pytest.mark.parametrize("args,label", STUB_CASES)
    def test_stub_does_not_write_files(self, args, label, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        run_cli(*args)
        written = list(tmp_path.rglob("*"))
        assert not written, f"{label!r} wrote files: {written}"


class TestDocumentAssemble:
    """drydock document assemble is wired to build_documentation.main()."""

    def test_document_assemble_builds_output(self, tmp_path):
        source = tmp_path / "spec.md"
        output = tmp_path / "index.html"
        source.write_text(
            "---\ntitle: Test\neyebrow: E\nsubtitle: S\nauthor: A\nstudio: St\nyear: 2026\n---\n\n# Body\n",
            encoding="utf-8",
        )
        rc, out, err = run_cli(
            "document", "assemble", "--source", str(source), "--output", str(output)
        )
        assert rc == 0
        assert output.exists()
        assert "Built documentation" in out

    def test_document_assemble_no_args_uses_defaults_or_exits(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        rc, out, err = run_cli("document", "assemble")
        # With no source available the default source path will not exist; exits non-zero.
        assert rc != 0 or "Built" in out

    def test_document_assemble_is_not_a_stub(self, tmp_path):
        source = tmp_path / "spec.md"
        source.write_text(
            "---\ntitle: T\neyebrow: E\nsubtitle: S\nauthor: A\nstudio: St\nyear: 2026\n---\n\n# B\n",
            encoding="utf-8",
        )
        rc, out, err = run_cli(
            "document", "assemble", "--source", str(source), "--output", str(tmp_path / "out.html")
        )
        combined = out + err
        assert "not implemented" not in combined.lower()


class TestRunQuarterdeck:
    """drydock run quarterdeck dispatches to quarterdeck_run.run_quarterdeck."""

    @staticmethod
    def _make_target(tmp_target_root, name: str = "MyTarget"):
        qd = tmp_target_root / name / "QuarterDeck"
        qd.mkdir(parents=True)
        # State-only console marker; the runtime is served from the package.
        (qd / "console.yaml").write_text("project: x\n", encoding="utf-8")
        return tmp_target_root / name

    def test_run_quarterdeck_dispatches(self, tmp_target_root, isolated_config, monkeypatch):
        from types import SimpleNamespace

        run_cli("config", "set", "drydock_workspace", str(tmp_target_root.parent))
        self._make_target(tmp_target_root)

        calls: list = []

        def fake_run(target_dir, *, port, host):
            calls.append({"target_dir": target_dir, "port": port, "host": host})
            return SimpleNamespace(exit_code=0)

        monkeypatch.setattr("drydock.quarterdeck_run.run_quarterdeck", fake_run)
        rc, out, err = run_cli("run", "quarterdeck", "MyTarget")
        assert rc == 0
        assert calls
        assert calls[0]["port"] == 8080
        assert calls[0]["host"] == "127.0.0.1"

    def test_run_shows_help_instead_of_stub(self):
        rc, out, err = run_cli("run")

        assert rc == 0
        assert "quarterdeck" in out
        assert "not implemented" not in out + err

    def test_run_quarterdeck_without_target_uses_sole_target(
        self, tmp_target_root, isolated_config, monkeypatch
    ):
        from types import SimpleNamespace

        run_cli("config", "set", "drydock_workspace", str(tmp_target_root.parent))
        target = self._make_target(tmp_target_root, "OnlyTarget")
        calls: list = []

        def fake_run(target_dir, *, port, host):
            calls.append({"target_dir": target_dir, "port": port, "host": host})
            return SimpleNamespace(exit_code=0)

        monkeypatch.setattr("drydock.quarterdeck_run.run_quarterdeck", fake_run)
        rc, out, err = run_cli("run", "quarterdeck")

        assert rc == 0
        assert calls == [{"target_dir": target, "port": 8080, "host": "127.0.0.1"}]
        assert str(target) in out

    def test_run_quarterdeck_custom_port(self, tmp_target_root, isolated_config, monkeypatch):
        from types import SimpleNamespace

        run_cli("config", "set", "drydock_workspace", str(tmp_target_root.parent))
        self._make_target(tmp_target_root)

        calls: list = []

        def fake_run(target_dir, *, port, host):
            calls.append(port)
            return SimpleNamespace(exit_code=0)

        monkeypatch.setattr("drydock.quarterdeck_run.run_quarterdeck", fake_run)
        rc, out, err = run_cli("run", "quarterdeck", "MyTarget", "--port", "9090")
        assert rc == 0
        assert calls[0] == 9090

    def test_run_quarterdeck_custom_host(self, tmp_target_root, isolated_config, monkeypatch):
        from types import SimpleNamespace

        run_cli("config", "set", "drydock_workspace", str(tmp_target_root.parent))
        self._make_target(tmp_target_root)

        calls: list = []

        def fake_run(target_dir, *, port, host):
            calls.append(host)
            return SimpleNamespace(exit_code=0)

        monkeypatch.setattr("drydock.quarterdeck_run.run_quarterdeck", fake_run)
        rc, out, err = run_cli("run", "quarterdeck", "MyTarget", "--host", "0.0.0.0")
        assert rc == 0
        assert calls[0] == "0.0.0.0"

    def test_run_quarterdeck_missing_app_py_raises(self, tmp_target_root, isolated_config):
        run_cli("config", "set", "drydock_workspace", str(tmp_target_root.parent))
        (tmp_target_root / "Empty").mkdir()
        rc, out, err = run_cli("run", "quarterdeck", "Empty")
        assert rc == 1
        assert "error" in err.lower()

    def test_run_quarterdeck_config_port_used(self, tmp_target_root, isolated_config, monkeypatch):
        from types import SimpleNamespace

        run_cli("config", "set", "drydock_workspace", str(tmp_target_root.parent))
        run_cli("config", "set", "quarterdeck_port", "7777")
        self._make_target(tmp_target_root)

        calls: list = []

        def fake_run(target_dir, *, port, host):
            calls.append(port)
            return SimpleNamespace(exit_code=0)

        monkeypatch.setattr("drydock.quarterdeck_run.run_quarterdeck", fake_run)
        rc, out, err = run_cli("run", "quarterdeck", "MyTarget")
        assert rc == 0
        assert calls[0] == 7777


APPROVED_PLAN_STATUS = """\
# BUILD_PLAN: TestTarget
state: approved
updated: 2026-01-01T00:00:00
plan_hash: abc123

## story 1: Core feature
id: core-feature
state: pending

## story 2: Done feature
id: done-feature
state: closed/verified
"""


class TestStatus:
    def _setup(self, tmp_target_root, monkeypatch):
        from drydock.init_specification import init_specification

        target_dir = tmp_target_root / "TestTarget"
        init_specification("TestTarget", target_dir)
        (target_dir / "BUILD_PLAN.md").write_text(APPROVED_PLAN_STATUS, encoding="utf-8")
        monkeypatch.setenv("DRYDOCK_WORKSPACE", str(tmp_target_root.parent))

    def test_status_blueprint_target_reports_plan_state(
        self, tmp_target_root, isolated_config, monkeypatch
    ):
        self._setup(tmp_target_root, monkeypatch)
        rc, out, err = run_cli("status", "TestTarget")
        assert rc == 0, err
        assert "TestTarget" in out
        assert "core-feature" in out

    def test_status_blueprint_reports_validation_summary(
        self, tmp_target_root, isolated_config, monkeypatch
    ):
        self._setup(tmp_target_root, monkeypatch)
        rc, out, err = run_cli("status", "TestTarget")
        assert rc == 0, err
        assert "TestTarget" in out
        assert "Blueprint" in out
        assert "0 errors" in out

    def test_status_no_args_no_activity_exits_zero(
        self, tmp_target_root, isolated_config, monkeypatch
    ):
        monkeypatch.setenv("DRYDOCK_WORKSPACE", str(tmp_target_root.parent))
        monkeypatch.chdir(tmp_target_root)
        rc, out, err = run_cli("status")
        assert rc == 0

    def test_status_no_args_configured_workspace_without_targets_recommends_init(
        self, tmp_path, isolated_config, monkeypatch
    ):
        workspace = tmp_path / "workspace"
        workspace.mkdir()
        run_cli("config", "set", "drydock_workspace", str(workspace))
        monkeypatch.chdir(workspace)

        rc, out, err = run_cli("status")

        assert rc == 0, err
        assert "drydock init <Target>" in out
        assert "config set drydock_workspace" not in out

    def test_status_no_args_shows_initialized_target(self, tmp_path, isolated_config, monkeypatch):
        from drydock.init_target import init_target

        workspace = tmp_path / "ws"
        workspace.mkdir()
        monkeypatch.setenv("DRYDOCK_WORKSPACE", str(workspace))
        init_target("MyProject", workspace / "targets")

        rc, out, err = run_cli("status")
        assert rc == 0, err
        assert "MyProject" in out
        assert "Next Step:" in out

    def test_activity_recorded_after_status_command(
        self, tmp_target_root, isolated_config, monkeypatch
    ):
        self._setup(tmp_target_root, monkeypatch)
        run_cli("status", "TestTarget")

        from drydock.config import get_last_activity

        activity = get_last_activity()
        assert activity["blueprint"] == "TestTarget"
        assert activity["target"] == "TestTarget"
        assert activity["command"] == "status"
        assert activity["time"] != ""

    def test_status_too_many_args_exits_2(self, tmp_target_root, isolated_config, monkeypatch):
        self._setup(tmp_target_root, monkeypatch)
        rc, out, err = run_cli("status", "A", "B", "C")
        assert rc == 2
